# Generated by Django 3.1.7 on 2021-04-09 12:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='title',
            field=models.CharField(help_text='Enter the place name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='type_of_place',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
