# Generated by Django 3.1.7 on 2021-04-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesapp', '0005_auto_20210412_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
